[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_staking_example = "Ae2Lvfpx6GaYMkogDrije7u5rQtyMySisyuSAqzXveET"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
